/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package servise;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.10.0)", date = "2018-03-18")
public class JsRefference implements org.apache.thrift.TBase<JsRefference, JsRefference._Fields>, java.io.Serializable, Cloneable, Comparable<JsRefference> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("JsRefference");

  private static final org.apache.thrift.protocol.TField SECTIONS_LIST_FIELD_DESC = new org.apache.thrift.protocol.TField("sectionsList", org.apache.thrift.protocol.TType.LIST, (short)1);
  private static final org.apache.thrift.protocol.TField AUTHOR_FIELD_DESC = new org.apache.thrift.protocol.TField("author", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new JsRefferenceStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new JsRefferenceTupleSchemeFactory();

  public java.util.List<Section> sectionsList; // required
  public Author author; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    SECTIONS_LIST((short)1, "sectionsList"),
    AUTHOR((short)2, "author");

    private static final java.util.Map<String, _Fields> byName = new java.util.HashMap<String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // SECTIONS_LIST
          return SECTIONS_LIST;
        case 2: // AUTHOR
          return AUTHOR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.SECTIONS_LIST, new org.apache.thrift.meta_data.FieldMetaData("sectionsList", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, Section.class))));
    tmpMap.put(_Fields.AUTHOR, new org.apache.thrift.meta_data.FieldMetaData("author", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "Author")));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(JsRefference.class, metaDataMap);
  }

  public JsRefference() {
  }

  public JsRefference(
    java.util.List<Section> sectionsList,
    Author author)
  {
    this();
    this.sectionsList = sectionsList;
    this.author = author;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public JsRefference(JsRefference other) {
    if (other.isSetSectionsList()) {
      java.util.List<Section> __this__sectionsList = new java.util.ArrayList<Section>(other.sectionsList.size());
      for (Section other_element : other.sectionsList) {
        __this__sectionsList.add(new Section(other_element));
      }
      this.sectionsList = __this__sectionsList;
    }
    if (other.isSetAuthor()) {
      this.author = new Author(other.author);
    }
  }

  public JsRefference deepCopy() {
    return new JsRefference(this);
  }

  @Override
  public void clear() {
    this.sectionsList = null;
    this.author = null;
  }

  public int getSectionsListSize() {
    return (this.sectionsList == null) ? 0 : this.sectionsList.size();
  }

  public java.util.Iterator<Section> getSectionsListIterator() {
    return (this.sectionsList == null) ? null : this.sectionsList.iterator();
  }

  public void addToSectionsList(Section elem) {
    if (this.sectionsList == null) {
      this.sectionsList = new java.util.ArrayList<Section>();
    }
    this.sectionsList.add(elem);
  }

  public java.util.List<Section> getSectionsList() {
    return this.sectionsList;
  }

  public JsRefference setSectionsList(java.util.List<Section> sectionsList) {
    this.sectionsList = sectionsList;
    return this;
  }

  public void unsetSectionsList() {
    this.sectionsList = null;
  }

  /** Returns true if field sectionsList is set (has been assigned a value) and false otherwise */
  public boolean isSetSectionsList() {
    return this.sectionsList != null;
  }

  public void setSectionsListIsSet(boolean value) {
    if (!value) {
      this.sectionsList = null;
    }
  }

  public Author getAuthor() {
    return this.author;
  }

  public JsRefference setAuthor(Author author) {
    this.author = author;
    return this;
  }

  public void unsetAuthor() {
    this.author = null;
  }

  /** Returns true if field author is set (has been assigned a value) and false otherwise */
  public boolean isSetAuthor() {
    return this.author != null;
  }

  public void setAuthorIsSet(boolean value) {
    if (!value) {
      this.author = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case SECTIONS_LIST:
      if (value == null) {
        unsetSectionsList();
      } else {
        setSectionsList((java.util.List<Section>)value);
      }
      break;

    case AUTHOR:
      if (value == null) {
        unsetAuthor();
      } else {
        setAuthor((Author)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case SECTIONS_LIST:
      return getSectionsList();

    case AUTHOR:
      return getAuthor();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case SECTIONS_LIST:
      return isSetSectionsList();
    case AUTHOR:
      return isSetAuthor();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof JsRefference)
      return this.equals((JsRefference)that);
    return false;
  }

  public boolean equals(JsRefference that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_sectionsList = true && this.isSetSectionsList();
    boolean that_present_sectionsList = true && that.isSetSectionsList();
    if (this_present_sectionsList || that_present_sectionsList) {
      if (!(this_present_sectionsList && that_present_sectionsList))
        return false;
      if (!this.sectionsList.equals(that.sectionsList))
        return false;
    }

    boolean this_present_author = true && this.isSetAuthor();
    boolean that_present_author = true && that.isSetAuthor();
    if (this_present_author || that_present_author) {
      if (!(this_present_author && that_present_author))
        return false;
      if (!this.author.equals(that.author))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetSectionsList()) ? 131071 : 524287);
    if (isSetSectionsList())
      hashCode = hashCode * 8191 + sectionsList.hashCode();

    hashCode = hashCode * 8191 + ((isSetAuthor()) ? 131071 : 524287);
    if (isSetAuthor())
      hashCode = hashCode * 8191 + author.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(JsRefference other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetSectionsList()).compareTo(other.isSetSectionsList());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSectionsList()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sectionsList, other.sectionsList);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetAuthor()).compareTo(other.isSetAuthor());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAuthor()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.author, other.author);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("JsRefference(");
    boolean first = true;

    sb.append("sectionsList:");
    if (this.sectionsList == null) {
      sb.append("null");
    } else {
      sb.append(this.sectionsList);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("author:");
    if (this.author == null) {
      sb.append("null");
    } else {
      sb.append(this.author);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class JsRefferenceStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public JsRefferenceStandardScheme getScheme() {
      return new JsRefferenceStandardScheme();
    }
  }

  private static class JsRefferenceStandardScheme extends org.apache.thrift.scheme.StandardScheme<JsRefference> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, JsRefference struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // SECTIONS_LIST
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list8 = iprot.readListBegin();
                struct.sectionsList = new java.util.ArrayList<Section>(_list8.size);
                Section _elem9;
                for (int _i10 = 0; _i10 < _list8.size; ++_i10)
                {
                  _elem9 = new Section();
                  _elem9.read(iprot);
                  struct.sectionsList.add(_elem9);
                }
                iprot.readListEnd();
              }
              struct.setSectionsListIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // AUTHOR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.author = new Author();
              struct.author.read(iprot);
              struct.setAuthorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, JsRefference struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.sectionsList != null) {
        oprot.writeFieldBegin(SECTIONS_LIST_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.sectionsList.size()));
          for (Section _iter11 : struct.sectionsList)
          {
            _iter11.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.author != null) {
        oprot.writeFieldBegin(AUTHOR_FIELD_DESC);
        struct.author.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class JsRefferenceTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public JsRefferenceTupleScheme getScheme() {
      return new JsRefferenceTupleScheme();
    }
  }

  private static class JsRefferenceTupleScheme extends org.apache.thrift.scheme.TupleScheme<JsRefference> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, JsRefference struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetSectionsList()) {
        optionals.set(0);
      }
      if (struct.isSetAuthor()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetSectionsList()) {
        {
          oprot.writeI32(struct.sectionsList.size());
          for (Section _iter12 : struct.sectionsList)
          {
            _iter12.write(oprot);
          }
        }
      }
      if (struct.isSetAuthor()) {
        struct.author.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, JsRefference struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TList _list13 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
          struct.sectionsList = new java.util.ArrayList<Section>(_list13.size);
          Section _elem14;
          for (int _i15 = 0; _i15 < _list13.size; ++_i15)
          {
            _elem14 = new Section();
            _elem14.read(iprot);
            struct.sectionsList.add(_elem14);
          }
        }
        struct.setSectionsListIsSet(true);
      }
      if (incoming.get(1)) {
        struct.author = new Author();
        struct.author.read(iprot);
        struct.setAuthorIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

